/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Arrays;
import servercommunication.Communicator;
import servercommunication.ServerException;
import javafx.util.Pair;

/**
 *
 * @author Giovani
 */
public class WelcomeGUI extends javax.swing.JFrame {

    private final Communicator communicator;

    /**
     * Creates new form Welcome
	 * @param communicator
     */
    public WelcomeGUI(Communicator communicator) {
        this.communicator = communicator;
        initComponents();
		clearWarnLabels();
    }
	
	private void clearWarnLabels() {
		jLabelWarnID.setText("");
		jLabelWarnPassword.setText("");
		jLabelWarnFullName.setText("");
		jLabelWarnLocation.setText("");
	}
	
	private void clearInputFields() {
		jTextFieldUsername.setText("");
		jPasswordField.setText("");
		jTextFieldFullName.setText("");
		jTextFieldLocation.setText("");
	}
	
	private boolean checkInputFields(String action) {
		clearWarnLabels();
		
		if ("".equals(jTextFieldUsername.getText()))
			jLabelWarnID.setText("This field is required!");
		else if (jPasswordField.getPassword().length == 0)
			jLabelWarnPassword.setText("This field is required!");
		else if (action.contains("register") && "".equals(jTextFieldFullName.getText()))
			jLabelWarnFullName.setText("This field is required!");
		else if (action.equals("registerEntpr") && "".equals(jTextFieldLocation.getText()))
			jLabelWarnLocation.setText("This field is required!");
		else return true;
		return false;
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogDon = new javax.swing.JButton();
        jButtonRegDon = new javax.swing.JButton();
        jButtonLogEntpr = new javax.swing.JButton();
        jButtonRegEntpr = new javax.swing.JButton();
        jButtonLogAdmn = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldFullName = new javax.swing.JTextField();
        jTextFieldLocation = new javax.swing.JTextField();
        jLabelFullName = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelWarnID = new javax.swing.JLabel();
        jLabelWarnPassword = new javax.swing.JLabel();
        jLabelWarnFullName = new javax.swing.JLabel();
        jLabelWarnLocation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonLogDon.setText("Log as Donator");
        jButtonLogDon.setFocusPainted(false);
        jButtonLogDon.setFocusable(false);
        jButtonLogDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogDonActionPerformed(evt);
            }
        });

        jButtonRegDon.setText("Register as Donator");
        jButtonRegDon.setFocusPainted(false);
        jButtonRegDon.setFocusable(false);
        jButtonRegDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegDonActionPerformed(evt);
            }
        });

        jButtonLogEntpr.setText("Log as Enterpreneur");
        jButtonLogEntpr.setFocusPainted(false);
        jButtonLogEntpr.setFocusable(false);
        jButtonLogEntpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogEntprActionPerformed(evt);
            }
        });

        jButtonRegEntpr.setText("Register as Enterpreneur");
        jButtonRegEntpr.setFocusPainted(false);
        jButtonRegEntpr.setFocusable(false);
        jButtonRegEntpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegEntprActionPerformed(evt);
            }
        });

        jButtonLogAdmn.setText("Log as Administrator");
        jButtonLogAdmn.setFocusPainted(false);
        jButtonLogAdmn.setFocusable(false);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitulo.setText("MicroEmprestimos");

        jLabelUsername.setText("Username");

        jLabelPassword.setText("Password");

        jLabelFullName.setText("Full Name");

        jLabelLocation.setText("Location");

        jLabelRegister.setText("(fill in all 4 fields)");

        jLabelWarnID.setText("tab4");

        jLabelWarnPassword.setText("melhor");

        jLabelWarnFullName.setText("identação");

        jLabelWarnLocation.setText("ever");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonLogDon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogEntpr, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogAdmn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonRegDon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRegister)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegEntpr)
                        .addGap(282, 282, 282))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPassword)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUsername)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWarnID)
                            .addComponent(jLabelWarnPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFullName)
                            .addComponent(jLabelLocation))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldLocation)
                            .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWarnFullName)
                            .addComponent(jLabelWarnLocation))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabelTitulo)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelWarnID))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword)
                    .addComponent(jLabelWarnPassword))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogDon)
                    .addComponent(jButtonLogEntpr)
                    .addComponent(jButtonLogAdmn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFullName)
                    .addComponent(jLabelWarnFullName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocation)
                    .addComponent(jLabelWarnLocation))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegDon)
                    .addComponent(jButtonRegEntpr)
                    .addComponent(jLabelRegister))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogDonActionPerformed
        clearWarnLabels();
		
		if (checkInputFields("login"))
			try {
				Pair<String,Float> userData = communicator.loginDonator(jTextFieldUsername.getText(),Arrays.toString(jPasswordField.getPassword()));
				new DonatorGUI(this, communicator,userData.getKey(),userData.getValue().toString()).setVisible(true);
				clearInputFields();
				this.setVisible(false);
			} catch (ServerException e) {
				jLabelWarnID.setText("Invalid ID and Password combination!");
			}
    }//GEN-LAST:event_jButtonLogDonActionPerformed

    private void jButtonLogEntprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogEntprActionPerformed
		if (checkInputFields("login"))
			try {
				String username = communicator.loginEntrepreneur(jTextFieldUsername.getText(),Arrays.toString(jPasswordField.getPassword()));
				new EnterpreneurGUI(this, communicator,username).setVisible(true);
				clearInputFields();
				this.setVisible(false);
			} catch (ServerException e) {
				jLabelWarnID.setText("Invalid ID and Password combination!");
			}
    }//GEN-LAST:event_jButtonLogEntprActionPerformed

    private void jButtonRegDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegDonActionPerformed
		if (checkInputFields("registerDon"))
			try {
				communicator.registerDonator(jTextFieldUsername.getText(),Arrays.toString(jPasswordField.getPassword()),jTextFieldFullName.getText());
				clearInputFields();
				jLabelWarnID.setText("Registration was a sucess!");
			} catch (ServerException e) {
				jLabelWarnID.setText("Invalid ID and Password combination!");
			}
    }//GEN-LAST:event_jButtonRegDonActionPerformed

    private void jButtonRegEntprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegEntprActionPerformed
		if (checkInputFields("registerEntpr"))
			try {
				communicator.registerEntrepreneur(jTextFieldUsername.getText(),Arrays.toString(jPasswordField.getPassword()),jTextFieldFullName.getText(),jTextFieldLocation.getText());
				clearInputFields();
				jLabelWarnID.setText("Registration was a sucess!");
			} catch (ServerException e) {
				jLabelWarnID.setText("Invalid ID and Password combination!");
			}
    }//GEN-LAST:event_jButtonRegEntprActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogAdmn;
    private javax.swing.JButton jButtonLogDon;
    private javax.swing.JButton jButtonLogEntpr;
    private javax.swing.JButton jButtonRegDon;
    private javax.swing.JButton jButtonRegEntpr;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWarnFullName;
    private javax.swing.JLabel jLabelWarnID;
    private javax.swing.JLabel jLabelWarnLocation;
    private javax.swing.JLabel jLabelWarnPassword;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
